### ISSUE TITLE
Documentation not reachable

### ISSUE THREAD

**Issue by timonmasberg** [cibernox/svelte-intl-precompile#58] opened 2022-09-19 08:52 UTC
https://svelte-intl-precompile.com/ seems to be not working anymore :( 404

**Comment by AM-77** [comment] 2022-10-11 16:47
you can access it via https://svelte-intl-precompile.com/en/docs/configuration, but https://svelte-intl-precompile.com/  still broken!

**Comment by cibernox** [comment] 2022-11-11 20:08
It's reachable again!! Something happened in the last month in sveltekit that the issue is now fixed

**Closed by cibernox** 2022-11-11 20:08 UTC
