### ISSUE TITLE
Got error after build

### ISSUE THREAD

**Issue by bitdom8** [cibernox/svelte-intl-precompile#17] opened 2021-09-20 15:06 UTC
Have tried also this : https://github.com/cibernox/sample-app-svelte-intl-precompile

    Cannot find package 'C:\Users\Administrator\Downloads\sample-app-svelte-intl-precompile-main\node_modules\.pnpm\svelte-intl-precompile@0.3.3_svelte@3.42.6\node_modules\precompile-intl-runtime\' imported from C:\Users\Administrator\Downloads\sample-app-svelte-intl-precompile-main\node_modules\.pnpm\svelte-intl-precompile@0.3.3_svelte@3.42.6\node_modules\svelte-intl-precompile\index.js

**Comment by bitdom8** [comment] 2021-09-23 13:14
The error persists with the pnpm run build command too

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Administrator\Documents\client\node_modules\.pnpm\svelte-intl-precompile@0.3.3_svelte@3.42.4\node_modules\svelte-intl-precompile\index.js
require() of ES modules is not supported.
require() of C:\Users\Administrator\Documents\client\node_modules\.pnpm\svelte-intl-precompile@0.3.3_svelte@3.42.4\node_modules\svelte-intl-precompile\index.js from C:\Users\Administrator\Documents\client\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\Administrator\Documents\client\node_modules\.pnpm\svelte-intl-precompile@0.3.3_svelte@3.42.4\node_modules\svelte-intl-precompile\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at nodeRequire (C:\Users\Administrator\Documents\client\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js:75155:17)
    at ssrImport (C:\Users\Administrator\Documents\client\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js:75097:20)
    at eval (/src/routes/login.svelte:13:37)
    at async instantiateModule (C:\Users\Administrator\Documents\client\node_modules\.pnpm\vite@2.5.10\node_modules\vite\dist\node\chunks\dep-36bf480c.js:75140:9)
```

**Comment by cibernox** [comment] 2021-11-19 16:42
I believe this is a duplicate of #10 where most of the conversation is happening.

**Closed by cibernox** 2021-11-19 16:42 UTC
